<%@include file="../../ppv_header.jsp"%>
<%
String cur_option = request.getParameter("cur_option");
String option_offset = request.getParameter("option_offset");
String status = request.getParameter("status");
String productId = request.getParameter("productid");
String backURL = request.getParameter("referrer");
String param = request.getHeader("referer");
//String param = request.getQueryString();
%>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<title> New Document </title>

    <link href="css/mh_style_e.css" rel="stylesheet" type="text/css">
    <script language="javascript" src="file:////javascript/iptv.js"></script>
    <script language="javascript">
		function MM_preloadImages() {
		  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
		    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
		    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
		}
		MM_preloadImages(
		'../../images/footer_pre_e.jpg',
		'../../images/footer_next_e.jpg',
		'../../images/footer_pre_next_e.jpg'
		);
		
		var urlParam = "productid=<%=productId%>&referrer=<%=backURL%>&<%=urlParam%>";
		var t_c_text = new Array();
t_c_text[0]="<b>1.	The now TV services we provide</b><br/><br/>1.1	We will provide you with a PIN to access your chosen now TV services set out in the Application for your private domestic viewing and access at the Premises.<br/><br/>1.2	All conditions and warranties relating to our supply of the now TV services, Equipment, devices and other goods implied by law are excluded to such extent permissible by law.<br/><br/>1.3	We shall use reasonable care and skill in providing our now TV services.  However, we cannot promise that our now TV services will be continuous or fault-free, or, the Equipment or devices we provide will never be faulty.";
t_c_text[1]="1.4	We decide the method, technical means and route that we use to provide the now TV services.<br/><br/>1.5	When you ask for a now TV service, we decide whether to provide it to you based on:<br/><br/>&nbsp;&nbsp;(a)	its availability to or coverage in the areas where you live or where the now TV services will be installed;<br/><br/>&nbsp;&nbsp;(b)	your eligibility for the now TV services;<br/><br/>&nbsp;&nbsp;(c)	you meeting our credit requirements;<br/><br/>&nbsp;&nbsp;(d)	whether you owe us any money for any services previously provided to you by us or any other PCCW group companies; and";
t_c_text[2]="&nbsp;&nbsp;(e)	whether the credit card information provided by you or any third party for payment of the now TV services is up to date and accurate.<br/><br/>&nbsp;&nbsp;If we decide not to provide the now TV services to you for any reason described in this clause 1.5, you agree that we can reject your Application for the now TV services without liability to you.<br/><br/><b>2.	Third party information or Content services</b><br/><br/>2.1 	Depending on your chosen now TV services, certain third party information or Content services provided by the Third Party Providers may also be available for access and use by you through the now TV services provided by us.  You agree to comply with the applicable terms and conditions";
t_c_text[3]="specified by us and/or such Third Party Providers if you choose to use their information or Content services.<br/><br/>2.2	In providing access to such third party information or Content services, you agree that we are not responsible or liable for:<br/><br/>&nbsp;&nbsp;(a)	the act, negligence or omission of such Third Party Providers;<br/><br/>&nbsp;&nbsp;(b)	your use of the information or Content services provided by such Third Party Providers; and<br/><br/>&nbsp;&nbsp;(c) 	the transaction or any dispute between you and such Third Party Providers.";
t_c_text[4]="<b>3.	now Select Services</b><br/><br/>3.1 	Terms applicable to now Select Monthly Term Plans Only<br/><br/>3.1.1	In respect of certain now Select Subscription Video on Demand Services as specified by us from time to time:<br/><br/>&nbsp;&nbsp;(a)	you can subscribe to a now Select Monthly Term Plan to view the programs on such now Select Subscription Video on Demand Services only if you subscribe to the specified channel on the now TV services; and";
t_c_text[5]="&nbsp;&nbsp;(b)	upon the termination of your subscription to such channel, your subscription to the relevant now Select Monthly Term Plan shall be automatically terminated at the same time.<br/><br/>3.1.2 	You can view the programs available under your now Select Monthly Term Plan for unlimited number of times during each month.<br/><br/>3.2 	Terms applicable to now Select Pay Per View Services only<br><br/>3.2.1 	You can view your AV-On Demand program once within 1.5 times of its duration by playing, pausing, fast forwarding and/or rewinding the program (\"<b>AV-On Demand Viewing Period</b>\").";
t_c_text[6]="3.2.2	Once you stop the transmission of any AV-On Demand program, your viewing of such program shall cease (notwithstanding that the AV-On Demand Viewing Period has not expired). You will have to pay the fees for the viewing of such program again if you wish to watch it thereafter.<br/><br/>3.2.3	You can access your selected now Select Pay Per View Service program (excluding AV-On Demand programs) anytime within the 48 hour period starting from the time you place an order for the viewing of such program, for viewing.<br/><br/>3.2.4	You will be charged a separate fee each time you place an order for the viewing of a now Select Pay Per View Service program.";
t_c_text[7]="3.2.5	You can purchase now DOLLAR which can be used to pay for your viewing of those now Select Pay Per View Service programs as specified by us from time to time. You will be billed for the purchase of now DOLLAR in your now TV bill for the month following your purchase.<br/><br/>3.2.6	You must use now DOLLAR to pay for the viewing of those now Select Pay Per View Service programs (for which now DOLLAR can be used for payment) if you have sufficient unused now DOLLAR in your account.<br/><br/>3.2.7	Notwithstanding any provision to the contrary in the Contract, your now DOLLAR will be forfeited if your subscription to the now TV services is terminated for whatever reason.";
t_c_text[8]="3.2.8	now DOLLAR has a validity period of 6 months which starts from the date of your purchase. All unused now DOLLAR cannot be used after the expiry of its validity period. If you top up your now DOLLAR before the validity period expires, the validity period will be extended for an additional 6 month period starting from the date of the top up.<br/><br/>3.2.9	You cannot exchange any unused now DOLLAR for cash, nor use them for anything else other than to pay for the viewing of those now Select Pay Per View Service programs as specified by us from time to time.<br/><br/>3.2.10	You can place an order to view a now Select Pay Per View Service program, through the now TV television portal only.";
t_c_text[9]="3.3 	Terms applicable to now Select Monthly Term Plans, now Select Pay Per View Services, and other free now Select Services<br/><br/>3.3.1	Please note that your viewing of a program under any now Select Monthly Term Plan and any free now Select Service will cease immediately:<br/><br/>&nbsp;&nbsp;(a)	if your WiFi connection is lost for whatever reason (applicable only to viewing of programs through the eye2 Device); or&nbsp;&nbsp;(b)	if your viewing of the program on the eye2 Device is interrupted by a call through the eye2 Device.<br/><br/>3.3.2	High definition programs and the now Select Pay Per View Programs will not be available for viewing through the eye2 Device.";
t_c_text[10]="3.3.3	No refund of any subscription or viewing fees or charges will be made to you under any circumstances (including when any program is not transmitted or if its transmission is interrupted or incomplete).<br/><br/>3.4	Channel switching cannot be done during the viewing of a program on any now Select Service. The transmission of a program may be interrupted at any time without any prior notice to you.<br/><br/><b>4.	Access and Installation</b><br/><br/>4.1	You agree to follow any reasonable instructions that we may give you, and to allow us safe access to your Premises for the provision or termination of the now TV services.";
t_c_text[11]="4.2	If you do not own the Premises, you agree to get the owner&#39;s permission for us to access the Premises and install our Equipment. You promise to us that you have such permission.<br/><br/>4.3	You agree that:<br/><br/>&nbsp;&nbsp;(a)	installation of the Equipment may not occur due to technical or other reasons beyond our reasonable control;<br/><br/>&nbsp;&nbsp;(b)	not more than two connections per modem will be set up by us to the now TV services;<br/><br/>&nbsp;&nbsp;(c)	that you will not use any other hardware in place of the Equipment to access the now TV services without our written consent; and";
t_c_text[12]="&nbsp;&nbsp;(d)	that we will not be liable for any loss or damage suffered by you or any other person arising directly or indirectly from our installation activities under this clause 4.<br/><br/><b>5.	Equipment</b><br/><br/>5.1	You agree to look after our Equipment that we provide to you. We may replace our Equipment at any time. You shall immediately return our Equipment to us at the address that we tell you if you or we end the Contract for the now TV services. If you do not do so or our Equipment is lost or damaged other than through fair wear and tear, you will have to pay for it to be repaired or replaced.";
t_c_text[13]="5.2	We are and shall remain as the owner of our Equipment, you shall not:<br/><br/>&nbsp;&nbsp;(a)	remove or tamper with any of our identification marks or labels on our Equipment;<br/><br/>&nbsp;&nbsp;(b)	remove or tamper with any components (including software) of our Equipment, avoid or remove any integrated circuit, anti-copying device or protection facility contained in any Equipment;<br/><br/>&nbsp;&nbsp;(c) 	permit anyone other than us or our contractors to repair or maintain our Equipment; <br/><br/>&nbsp;&nbsp;(d)	sell, transfer or part with the possession or control of our Equipment;";
t_c_text[14]="&nbsp;&nbsp;(e)	connect any Equipment to more than one television set or to any other equipment or device (other than a television set in the Premises); and<br/><br/>&nbsp;&nbsp;(f)	use the Equipment for business purposes.<br/><br/>5.3	Our Equipment may be shared by any PCCW group company for providing its services in your Premises.<br/><br/>5.4	For certain devices not provided by us (such as, mobile handsets for mobile services and USB modems for Netvigator services), we have no responsibility to provide repair and maintenance services for such devices.  Instead, the manufacturers of such devices will provide warranty and maintenance services directly to you.";
t_c_text[15]="5.5	If you buy or rent a decoder which proves to be defective under normal use due to defective materials, design and/or workmanship, we shall provide you with such repair or replacement services as specified by us from time to time.  Notwithstanding the aforesaid, we shall not be responsible for repairing or replacing any decoder damaged as a result of any use that is not authorized under the Contract.<br/><br/>5.6	If any other Equipment (other than the decoder provided by us) proves to be defective under normal use due to defective materials, design and/or workmanship, we will at our option either repair or replace such Equipment. ";
t_c_text[16]="5.7	We have the right to repossess any Equipment, or terminate or suspend its use, at any time without advance notice for the purposes of compliance with applicable law, regulations, licence conditions, our obligations with third parties or threat of legal action, or if we reasonably believe such repossession, termination or suspension may be required to enable us to comply with the foregoing. <br/><br/>5.8	Upon termination of the rental of or the right to use the Equipment for whatever reason, you agree to promptly return all Equipment to us in good and clean condition, and that we will not be returning any amount prepaid by you for renting or using the Equipment. <br/><br/><b>6.	When we provide the now TV services</b>";
t_c_text[17]="6.1	Your Contract with us starts on the date we accept your application for the now TV services.<br/><br/><b>7.	Cancellation of Application</b><br/><br/>&nbsp;&nbsp;If you cancel your Application before the now TV services installation date, you shall pay the Pre-Activation Cancellation Charge.<br/><br/><b>8.	Security deposit</b><br/><br/>8.1	At any time, you may need to pay a deposit or a payment upfront before you can receive the now TV services, Equipment, device or other goods provided by us. The amount of such deposit or upfront payment shall be determined by us.";
t_c_text[18]="8.2	Our acceptance of any form of deposit or upfront payment from you does not affect any of your responsibilities under the Contract.<br/><br/>8.3	If you or we end your subscription to any now TV service, Content or the Contract and unless otherwise specified in the Contract, we will return the deposit or upfront payment free of any interest to you less any outstanding Charges you owe us within a reasonable time.<br/><br/><b>9.	Payment for the now TV services</b><br/><br/>9.1	You agree to pay all Charges for the now TV services, Content, Equipment, devices and any other goods we provide to you, whether you use the now TV services or someone else does.";
t_c_text[19]="9.2	If you use the now TV services to access a service provided by someone else, and we are charged for such other service, you must pay us for such other service.<br/><br/>9.3	We may issue a monthly bill to you. We will normally bill you upfront (in advance) for the Charges and any Rental Charges for the Equipment. We will bill you later for any usage Charges for certain now TV services which are billed accordingly to usage (such as pay per view services). If possible, Charges will appear on your next bill, but sometimes Charges may appear on a later bill.";
t_c_text[20]="9.4	Our records are sufficient proof that a Charge for the now TV services is payable by you unless they are shown to be incorrect. We may re-issue any bill if there is any error in the bill.<br/><br/>9.5	We will send your bills to the address where the now TV services are provided or to your specified email address unless otherwise agreed by us. You may also view your bills on your now TV television portal.  <br/><br/>9.6	We will send your first bill shortly after we have provided the now TV services to you for the first time. After that, we will send bills at regular intervals. However, we may send you a bill at a different time.";
t_c_text[21]="9.7	We can bill you through a billing agent or any PCCW group companies.<br/><br/>9.8	You agree to pay the Charges for the now TV services without deduction before the Due Date unless otherwise agreed by us. If you think that the Charges on your bill are incorrect and wish to dispute those Charges, you must tell us within 15 days of the bill date. You must pay all Charges that are not disputed.<br/><br/>9.9	If you do not pay your bill, you shall pay us interest for the overdue amount at an interest rate equal to 2% above the prime lending rate of The Hongkong and Shanghai Banking Corporation Limited until full payment.";
t_c_text[22]="9.10	We may also charge you the administrative fee and the relevant bank charges for any direct debit or cheque payments which are returned to us because you do not have enough funds in your account.<br/><br/>9.11	We will generally not suspend or end your subscription to the now TV services for non-payment of your bill until at least 15 days after your payment was due. If however you have failed to pay on time a recent bill or have failed to pay a bill on many occasions, we may end or suspend your access to the now TV services earlier than 15 days.";
t_c_text[23]="9.12	If you do not pay your bill, we may ask a debt-collection agency to collect the payment on our behalf. If we do so, you will have to pay us an extra amount for breaching the Contract. This will not be more than the reasonable costs we have to pay the agency, who will add the amount to your debt on our behalf (this will depend on the amount you owe us). We may also charge a handling fee, reconnection fee and/or require a security deposit if your access to the now TV services is suspended or terminated before payment is made.<br/><br/>9.13	Please note that no credit or refund is available in respect of any time when the now TV services or any part thereof is disrupted or suspended for maintenance or as a result of technical difficulties or a circumstance beyond our";
t_c_text[24]="reasonable control.<br/><br/>9.14	If you have used or permitted any other person to use or access the now TV services or Content in breach of sub-clause 10.2(b) or 10.2(c), we reserve the right to charge you:<br/><br/>&nbsp;&nbsp;(a)	subscription fees at the full published rates applicable to commercial subscribers for the now TV services or Content;<br/><br/>&nbsp;&nbsp;(b)	liquidated damages at the rate of 2% per month on these subscription fees chargeable at such published rates as referred to in the preceding sub-clause 9.14(a); and";
t_c_text[25]="&nbsp;&nbsp;(c)	any administrative or service charges; until the cessation of such use or access.<br/><br/>9.15	We shall not be obliged to extend the Fixed Term of your Service Plan (if any) to the now TV services and/or any Content on a pro-rata basis for the period that your access to the now TV services and/or any Content was suspended as a result of your failure to make payment of your invoice by its Due Date.<br/><br/><b>10.	Your use of the now TV services</b><br/><br/>10.1	In your use of the now TV services and Content, you must always follow the applicable law and the terms of the Contract and any other relevant terms and conditions applicable to such services";
t_c_text[26]="and content. You agree that the use of the now TV services and Content by any other users, whether authorised by you or not, shall be regarded to be the use of the now TV services and Content by you.<br/><br/>10.2	You:<br/><br/>&nbsp;&nbsp;(a)	must not, and must not permit any other person to, sell, reproduce, copy, distribute, modify, exploit the now TV services and/or Content or reverse engineer any Content consisting of downloadable software;<br/><br/>&nbsp;&nbsp;(b)	agree that the now TV services and Content are only for your private domestic viewing and access at the Premises and shall not yourself, or";
t_c_text[27]="permit any other person to, show, play, use, access or view the now TV services or Content for any public or commercial purposes and/or within any public place or commercial premises or on any device in any place outside the Premises;<br/><br/>&nbsp;&nbsp;(c)	without limiting sub-clause 10.2(b), shall not charge for use or access to the now TV services or any Content or for access to any premises where the now TV services or Content are viewed;<br/><br/>&nbsp;&nbsp;(d)	must not, or permit any other person to, or cause the now TV services or any Content to be transmitted, re-transmitted or broadcast or included in a cable program service, by any means including the Internet;";
t_c_text[28]="&nbsp;&nbsp;(e)	without limiting sub-clause 10.2(d), must not (except for connecting to a television set in the Premises) transmit, arrange for or authorize<br/><br/>the transmission of any now TV services or Content to any device including without limitation any personal computer, television receiver or mobile device or to any place or device outside the Premises; and<br/><br/>&nbsp;&nbsp;(f)	must not, or permit any other person to, copy, encode, digitize, reformat, compress, intercept, interfere, or tamper with or otherwise manipulate the signals of the now TV services or Content including";
t_c_text[29]="output signals of the Equipment in any way and by any means.<br/><br/>Our authorization for you to access and receive the now TV services is conditional upon your strict compliance with each of the above conditions and the other terms and conditions of the Contract.<br/><br/>10.3	You acknowledge and agree that:<br/><br/>&nbsp;&nbsp;(a)	it is not our policy to exercise any editorial control over or to edit or amend any now TV services and/or Content not produced by us before it is transmitted or made available through the now TV services;";
t_c_text[30]="&nbsp;&nbsp;(b)	nothing you do on or in relation to the now TV services, Content and/or Equipment will transfer any intellectual property rights or license you to exercise any intellectual property rights;<br/><br/>&nbsp;&nbsp;(c)	many channels, programs and other Content on the now TV services are provided by third party providers, not by us. Their availability, and the availability of programs on such channels, are outside our control;<br/><br/>&nbsp;&nbsp;(d)	we make no representation, promise, warranty, undertaking or guarantee as to the quality or continuity of any particular Content;";
t_c_text[31]="&nbsp;&nbsp;(e)	you have not relied upon any information or statement to the effect that any particular Content will be made available to you for the whole or part of the term of your subscription to the now TV services;<br/><br/>&nbsp;&nbsp;(f)	we can vary, replace or withdraw any channels and programs (whether advertised or not); and<br/><br/>&nbsp;&nbsp;(g)	we can change or reduce the number of hours of broadcast of any channel or any program on any channel.";
t_c_text[32]="10.4	You shall not use any equipment or device that may harm our Network or other customers&#39; equipment.  If you do so, you must disconnect it immediately.<br/><br/>10.5	When you are using the now TV services at the same time as the NETVIGATOR Broadband service, there will be a reduction in the bandwidth of the NETVIGATOR Broadband service.<br/><br/><b>11.	PINS</b><br/><br/>11.1	You are responsible for properly using any user IDs, PINs and passwords for the now TV services, if any, and must take all necessary steps to make sure that you keep these confidential and secure, use them properly and do not make these";
t_c_text[33]="available to unauthorised people. You agree to tell us immediately if you discover any unauthorised use of the user IDs, PINs and passwords.<br/><br/>11.2	Please note that there may be some Content which is not suitable for viewing or which must not be viewed or subscribed by or made accessible to minors. In this regard, we will provide you with a PIN to, amongst other things, access such Content. We will not be responsible for any uses of the PIN we provide to you to access the now TV services (including access to, subscribing and viewing of any Content).<br/><br/><b>12.	Ending Your Subscription to the now TV services</b>";
t_c_text[34]="12.1	We can end your subscription to any now TV service or the Contract by giving you 30 days&#39; advance written notice.<br/><br/>12.2	Once we have provided the now TV services, you may tell us to end your subscription to any now TV service or the Contract at any time by giving us 30 days&#39; written advance notice. You shall only give such notice to us by completing our termination form or such other means as required by us from time to time. The Contract or your subscription to any now TV service shall end only 30 days after our confirmation to you of the same.<br/><br/>12.3	Unless otherwise agreed by us, the Contract automatically ends if the installation of any Equipment does not occur for any reason.";
t_c_text[35]="12.4	If within any relevant Fixed Term for any now TV service, you choose to end your subscription to such now TV service or the Contract by giving us 30 days&#39; advance written notice where we have not breached any terms of the Contract, except as described in clauses 13.2 and 21.4, you will have to pay us the Early Termination Charges and any other Cancellation Charges.<br/><br/>12.5	Upon the end of your subscription to any now TV service or the Contract, we will first take off any money that (a) you owe us under such subscription, the Contract or any other contract between us; and (b) you owe any other PCCW group company under any other contract between you and such PCCW group company. Where we provide you with a range";
t_c_text[36]="of services and you owe us money for some services, we reserve the right to charge you for such services via the bills we send you for your other services, unless there is a genuine dispute between us regarding such services. <br/><br/>12.6	Upon the end of your subscription to any now TV service or the Contract for any reason, we will not be providing any refund of any amount prepaid by you in advance. <br/><br/>12.7	Even if your subscription to any bundled package of services (which include the now TV services) has ended, we may agree with you to continue to provide you with certain now TV services and you may retain the Equipment at your Premises to receive such now TV services.";
t_c_text[37]="<b>13.	Moving your home</b><br/><br/>13.1	If you change the installation address for the now TV services within Hong Kong, we will continue to provide your now TV services at your new address if there is coverage of the now TV services at the new address.  If you move your home, you shall provide us with sufficient proof that you are residing at the new address. We may also charge you a Moving Charge and any other Charges specified by us in the Application. <br/><br/>13.2 	If there is no coverage for the now TV services at your new installation address, you may choose to end your subscription to any now TV service or the Contract in accordance with clause 12.2.";
t_c_text[38]="Even if you choose to end your subscription to any now TV service or the Contract before the end of the Fixed Term, we may not charge you the Early Termination Charges.  However, unless we tell you otherwise, we may charge you the other Cancellation Charges.<br/><br/><b>14.	Our rights when we provide the now TV services</b><br/><br/>14.1	We may need to:<br/><br/>&nbsp;&nbsp;(a)	interrupt or suspend the now TV services (for example, for maintenance, repair, testing or upgrade of our Network or Equipment). If we do so, we will restore it as quickly as we can and we have no responsibility to pay you any compensation for any";
t_c_text[39]="loss resulting from such interruption or suspension; <br/><br/>&nbsp;&nbsp;(b)	suspend your access to the now TV services without notice where you have not (i) subscribed to any pay channel with us; and (ii) accessed any now TV service for a period of no less than three (3) consecutive months; and<br/><br/>&nbsp;&nbsp;(c)	modify or withdraw any of the now TV services and/or any Content; remove, disable or suspend transmission of any now TV service and/or Content which we consider in our sole opinion, breaches any applicable law, regulation or regulatory directive or to be otherwise unacceptable.<br/><br/><b>15.	Our responsibility to you when we provide the now TV services</b>";
t_c_text[40]="15.1	We accept responsibility if you are injured or die as a result of our negligence in the provision of the now TV services. We will not exclude or limit this responsibility.<br/><br/>15.2	We also accept responsibility for loss or damage to your physical property arising from our negligence. We will only pay you up to the Contract Value for this loss or damage.<br/><br/>15.3	In the absence of our negligence or deliberate wrongful act, we will not be liable to you for:<br/><br/>&nbsp;&nbsp;(a)	any damage to or loss of data suffered by you arising from your use of the now TV services, any Equipment and/or any Content;";
t_c_text[41]="&nbsp;&nbsp;(b)	any claim based in contract, tort, or otherwise for any loss of revenue (whether direct or indirect), loss of profits or any consequential loss whether of an economic nature or not;<br/><br/>&nbsp;&nbsp;(c)	any claim relating to any now TV service and/or Content supplied, provided, sold or made available by us (or any failure or delay to so supply or continue to supply, provide, sell or make available);<br/><br/>&nbsp;&nbsp;(d)	any disruption or suspension of the now TV services, Equipment or any part thereof which is attributable to an event or circumstance beyond our reasonable control; and";
t_c_text[42]="&nbsp;&nbsp;(e)	any damage or loss suffered by any third person arising from any installation, de-installation or reconnection of any Equipment carried out by you or with your knowledge and/or consent.<br/><br/>15.4 	Except as described in clause 15.1 and to such extent permissible by law, we will not pay you more than the Contract Value in compensation (even if we have been negligent) for all our liabilities under the Contract for the now TV services, Equipment, devices and any other goods we supplied or provided.<br/><br/><b>16.	Matters beyond our reasonable control</b>";
t_c_text[43]="&nbsp;&nbsp;Sometimes, we may not be able to do what we have agreed because of an event beyond our reasonable control (for example because of fire or flood or severe weather). In these cases, we do not accept responsibility for the delay or failure to provide you with your chosen now TV services in accordance with the Contract.  You or we can end the Contract immediately if such event lasts for a continuous period of no less than 30 days.<br/><br/><b>17.	If you breach the Contract</b><br/><br/>17.1	For serious misuse described in clauses 5.2 and 10.2, we may suspend or end the Contract immediately. Otherwise, if you breach the Contract, we will normally give you an opportunity to put matters right within 15 days after we inform you of";
t_c_text[44]="such breach before we suspend or end the Contract. However, if you do not do so, we may suspend or end the Contract.<br/><br/>17.2	We may also suspend or restrict your access to the now TV services or end the Contract if you breach any other contract you have with us or any of the PCCW group companies and do not put matters right within the time mentioned in such other contract. If we suspend your access to the now TV services or end the Contract, we will tell you what needs to be done before we can restore the now TV services.<br/><br/>17.3	If we end the Contract or your subscription for any now TV service within its Fixed Term under clause 17.1, 17.2, 18(c) or 18(d), you will have to";
t_c_text[45]="make immediate payment of all accrued charges, the Early Termination Charges and any other Cancellation Charges.<br/><br/>17.4	You agree to indemnify us, our content providers, service providers, sub-contractors, licensors and agents against any action, liability, cost, claim, loss, damage, proceeding and/or expense suffered or incurred by us and them arising from or which is related to:<br/><br/>&nbsp;&nbsp;(a)	your use, and any other person&#39;s use of the now TV services by virtue of the Equipment provided to you;<br/><br/>&nbsp;&nbsp;(b)	any breach of any term of the Contract by you; ";
t_c_text[46]="&nbsp;&nbsp;(c)	any theft, loss and/or damage caused to the Equipment provided to you on rental or complimentary basis provided that your maximum liability under this sub-clause 17.4(c) is HK$5,000; and<br/><br/>&nbsp;&nbsp;(d)	any installation, de-installation or reconnection of any Equipment carried out by you or with your knowledge and/or consent.<br/><br/><b>18.	Our other rights to suspend/end your subscription to the now TV services</b><br/><br/>&nbsp;&nbsp;We can limit, suspend or restrict your access to the now TV services, end the Contract, or end any subscription to any now TV services by giving you 15 days&#39; advance notice (to the extent that it is";
t_c_text[47]="reasonably practicable to do so) if:<br/><br/>&nbsp;&nbsp;(a)	the law requires us to do so;<br/><br/>&nbsp;&nbsp;(b)	there is an emergency that affects our ability to provide the now TV services;<br/><br/>&nbsp;&nbsp;(c) 	you become bankrupt or insolvent or appear likely to be;<br/><br/>&nbsp;&nbsp;(d)	you breach any term of the Contract; <br/><br/>&nbsp;&nbsp;(e)	such now TV service or any relevant Content is withdrawn from distribution through the now TV services for whatever reason;";
t_c_text[48]="&nbsp;&nbsp;(f)	we no longer hold the right to distribute such now TV services or Content;<br/><br/>&nbsp;&nbsp;(g)	we fail to obtain, hold, retain or renew any relevant regulatory approvals or if any relevant regulatory approvals are revoked or if it is required by a relevant authority to cease transmission of any such now TV service and/or Content; or<br/><br/>&nbsp;&nbsp;(h)	such now TV service or Content including any advertising therein fails to comply with any regulatory standards, relevant laws or any requirements or orders issued from time to time by a relevant authority.<br/><br/><b>19.	Privacy</b>";
t_c_text[49]="19.1	We collect, process, disclose, retain or use your Personal Data in accordance with the PCCW Privacy Policy Statement which is published on www.pccw.com/legal/privacy.html.<br/><br/>19.2	If we request Personal Data from you, you may refuse to provide the Personal Data. However, we may decline to provide the now TV services to you.<br/><br/>19.3	You will, as soon as possible, tell us of any change of address or any other particulars provided to us which may affect our provision of the now TV services to you.<br/><br/><b>20.	Information Provisioning</b>";
t_c_text[40]="&nbsp;&nbsp;You will provide us with the information relating to you or your use of the now TV services we reasonably require:<br/><br/>&nbsp;&nbsp;(a)	to help us in complying with the applicable law and to report to any Government Agency regarding such compliance; and<br/><br/>&nbsp;&nbsp;(b)	to assess whether or not you have complied, are complying and will be able to continue to comply with all obligations under the Contract.<br/><br/><b>21.	Changing the terms</b><br/><br/>21.1	Sometimes, we will need to unilaterally change the Charges or the terms and conditions of the now TV services covered by the Contract. We will";
t_c_text[51]="publish details of all changes online at www.now-tv.com.<br/><br/>21.2	We will also let you know about a price increase or a change to the terms and conditions that we believe is likely to cause you material disadvantage at least 30 days before it happens.<br/><br/>21.3	For changes we need to make to meet legal and regulatory requirements, we may not be able to meet the timescale specified in clause 21.2. We will let you know about these changes as soon as we can.<br/><br/>21.4	If we:";
t_c_text[52]="&nbsp;&nbsp;(a)	increase the Charges for any now TV service or any Rental Charges as set out in the Application (other than Administrative and Usage Based Charges); or<br/><br/>&nbsp;&nbsp;(b)	change the terms and conditions of the now TV services which is to your material disadvantage,<br/><br/>you will not have to pay the Early Termination Charges and any other Cancellation Charge if you decide to end your subscription to the relevant now TV service early. However, once we have told you about such a change, you must let us know that you want to end your subscription to that now TV service within 30 days. The Contract will continue to apply to any other now TV services that are not affected by any changes that we make.";
t_c_text[53]="<b>22.	Other things we need to tell you</b><br/><br/>22.1	You accept that the Contract is personal to you and agree not to transfer it to anyone else, or to try to do so without our prior written consent. However, we may take instructions from a person who we think, with good reason, is acting with your permission.<br/><br/>22.2	We can transfer our rights and obligations under the Contract to any person or entity without your consent. We can also use an agent or subcontractor to perform our responsibilities.<br/><br/>22.3	When we need to contact you, we will use your billing address, e-mail address, mobile or fixed phone number that you provide us for contacting";
t_c_text[54]="you. If you need to contact us, please use the address on your last bill or any other postal address, e-mail address or phone number we have given to you for that purpose.<br/><br/>22.4	The notice or communication sent by us shall be treated as received by you: (a) 3 days after posting, if sent by letter; (b) at the time of delivery, if delivered in person; (c) immediately upon faxing if sent by fax and the transmission report indicates that the fax transmission was successful; or (d) immediately upon sending the email, if sent by email.";
t_c_text[55]="22.5	The Contract is governed by the laws of Hong Kong and you agree to submit to the exclusive jurisdiction of the Hong Kong courts.<br/><br/>22.6	At the end of the your subscription to any now TV service or the existing Contract, if (a) we are unable to contact you; (b) you do not contact us; or (c) you are undecided as to whether to renew your subscription or the existing Contract, you agree that we shall, subject to clause 22.7, continue to provide the now TV services to you on the terms of such subscription or the existing Contract on a month to month basis until you end such subscription or the existing Contract by giving us at least 30 days&#39; advance written notice (or any other period we specify in the Application). While we";
t_c_text[56]="provide the relevant now TV services to you on a monthly basis, instead of charging you at the rate payable by you for the preceding Fixed Term, we will charge you for these services at the prevailing monthly rate published from time to time on our website www.now-tv.com.<br/><br/>22.7	Unless we tell you otherwise, all the free gifts, free products, free viewing, free services, waivers, discount or rebate offered by us during the duration of the existing Contract shall not be offered by us during the monthly periods mentioned in clause 22.6.<br/><br/>22.8 	Clause 22.6 shall not apply to the subscription of services which does not have a Fixed Term such as pay per view services on the now TV services. ";
t_c_text[57]="22.9	Please note that certain channels on the now TV services cannot be received on Lamma Island and a different decoder will be required to receive the now TV services on Lamma Island.<br/><br/>22.10	If any term or condition of the Contract becomes or is declared illegal, invalid or unenforceable for any reason, such term or condition shall be divisible from the Contract and shall be deemed to be deleted from the Contract.<br/><br/>22.11	If these now TV Terms and Conditions, the now TV Services Menus and the Application conflict with each other, the";
t_c_text[58]="inconsistency will be resolved in the descending order of preference set out in this clause.<br/><br/><b>23.	Special meanings</b><br/><br/>&nbsp;&nbsp;In the Contract: <br/><br/>&nbsp;&nbsp;<b>Administrative and Usage Based Charges</b>&nbsp;means the administrative Charges (such as lost and replacement Charges) and usage based Charges (such as Charges for pay per view services and other interactive services on the now TV services).<br/><br/>&nbsp;&nbsp;<b>Application</b>&nbsp;means a written application and, where expressly allowed by us, a non-written application made by you to us requesting the";
t_c_text[59]="provision of the relevant now TV services to you. For clarity, the term Application includes the Service Plan for the relevant now TV service.<br/><br/>&nbsp;&nbsp;<b>AV-On-Demand</b>&nbsp;means the pay per view adult content service on the now Select Services which is restricted to viewers of 18 years or above.<br/><br/>&nbsp;&nbsp;<b>Cancellation Charge</b>&nbsp;means the cancellation charge for the now TV services, Equipment and any other devices provided by us as set out in the Application or as specified by us from time to time.";
t_c_text[50]="&nbsp;&nbsp;<b>Charges</b>&nbsp;means the charges and fees (including the Rental Charges) payable by you to us in respect of the provision of the now TV services, Equipment, devices or any other goods by us and as specified by us in these now TV Terms and Conditions, the Application and the now TV Services Menus (where applicable and as amended by us from time to time).<br/><br/>&nbsp;&nbsp;<b>Commencement Date</b>&nbsp;means the date that the now TV services are made available to you at your Premises.<br/><br/>&nbsp;&nbsp;<b>Content</b>&nbsp;means any data, information, images, graphics, video or audio content, applications, downloadable files or other multimedia content that can be accessed using the now TV services.";
t_c_text[61]="&nbsp;&nbsp;<b>Contract</b>&nbsp;means the contract between you and us in respect of the now TV services provided by us to you which is made up of these now TV Terms and Conditions, the Application, the terms and conditions attached thereto, and the now TV Services Menus (where applicable and as amended by us from time to time).<br/><br/>&nbsp;&nbsp;<b>Contract Value</b>&nbsp;means in relation to (a) the Service Plan subscribed by you, the total Charges for the Fixed Term payable by you to us under the Contract; or (b) any Service Plan (without a Fixed Term) subscribed by you, the total Charges paid by you to us for the period from the Commencement Date to the date immediately preceding any incident giving rise to your claim.";
t_c_text[62]="&nbsp;&nbsp;<b>Due Date</b>&nbsp;means the date specified by us in the relevant invoice for the payment of the Charges, or if no such date is specified, the date which is 20 days from the date of the invoice.<br/><br/>&nbsp;&nbsp;<b>Early Termination Charge</b>&nbsp;means the early termination charge payable by you to us as set out in the Application or as specified by us from time to time.<br/><br/>&nbsp;&nbsp;<b>Equipment</b>&nbsp;includes without limitation the now TV signal decoder, any remote control handset, power supply unit and/or cable for use of the decoder and all other equipment specified on the now TV Service Provisioning Equipment Delivery Note provided by us and/or our affiliates to make available the now TV services to you.";
t_c_text[63]="&nbsp;&nbsp;<b>eye2 Device</b>&nbsp;means the eye2 device (including the WiFi tablet, lithium polymer rechargeable battery, charging dock (if applicable) and AC-DC power adaptor) distributed by Hong Kong Telecommunications (HKT) Limited, for access to the eye2 Communication Package provided by Hong Kong Telecommunications (HKT) Limited. <br/><br/>&nbsp;&nbsp;<b>Fixed Term</b>&nbsp;means the fixed term for the now TV services as specified by us in the Application.<br/><br/>&nbsp;&nbsp;<b>Government Agency</b>&nbsp;means any government or governmental, semi-governmental, administrative, fiscal or judicial body, department, commission, authority, tribunal, agency or entity in any part of the world and includes the Broadcasting Authority";
t_c_text[64]=", the Television and Entertainment Licensing Authority and Telecommunications Authority of Hong Kong.<br/><br/>&nbsp;&nbsp;<b>Hong Kong</b>&nbsp;means the Hong Kong Special Administrative Region of the People&#39;s Republic of China.<br/><br/>&nbsp;&nbsp;<b>Licence</b>&nbsp;means a licence issued by a Government Agency to us from time to time authorising us to provide the now TV services.<br/><br/>&nbsp;&nbsp;<b>Moving Charge</b>&nbsp;means the Charge as specified by us in the Application or from time to time, that we charge you for the relocation of the now TV services in accordance with clause 13.1.";
t_c_text[65]="<b>Network</b>&nbsp;means the telecommunications network owned or operated by us in accordance with our Licence including all facilities and associated equipment used in, or in connection with, that network.<br/><br/><b>now DOLLAR</b>&nbsp;means the credits which you can purchase from us to pay for the viewing of those now Select Pay Per View Service programs as specified by us from time to time.<br/><br/><b>now Select Pay Per View Service</b>&nbsp;means any pay per view service on the now Select Services for which you have to pay a separate charge (and not a monthly subscription fee) for each viewing of a program on such service.";
t_c_text[66]="<b>now Select Monthly Term Plan</b>&nbsp;means any Service Plan for any now Select Subscription Video on Demand Service.<br/><br/><b>now Select Services</b>&nbsp;means the now Select Subscription Video On Demand Services, now Select Pay Per View Services, all video on demand services provided by us on a free of charge basis on the now TV services, and includes without limitation those services currently named now Video Express Unlimited, now Video Express First and AV-On-Demand.<br/><br/><b>now Select Subscription Video On Demand Service</b>&nbsp;means any video on demand service on the now Select Services for which you have to pay";
t_c_text[67]="a monthly subscription charge (and not a per program or per exhibition fee) to view the programs on such service during your subscription period to such service.<br/><br/><b>now TV services</b>&nbsp;means the television programme services and other services you are authorized to access from time to time on our television service, now TV.<br/><br/><b>now TV Services Menu</b>&nbsp;means each now TV services menu which sets out the Charges for the now TV services in relation to certain Service Plans, as amended by us from time to time.";
t_c_text[68]="<b>Other Charges</b>&nbsp;means those Charges which are identified as \"Other Charges\" in the Application.<br/><br/><b>Personal Data</b>&nbsp;has the same meaning given to it in the Personal Data (Privacy) Ordinance (Chapter 486, the Laws of Hong Kong).<br/><br/><b>PIN</b>&nbsp;means a personal identification number issued by us to you for your access to the now TV services.<br/><br/><b>Pre-Activation Cancellation Charge</b>&nbsp;means the Charges specified by us in the Application or from time to time, for the cancellation of the relevant Application in accordance with clause 7.";
t_c_text[69]="<b>Premises</b>&nbsp;mean the place where the now TV services are installed and used from time to time. <br/><br/><b>Rental Charges</b>&nbsp;means the periodical Charges payable by you to us in respect of the Equipment and as specified by us in the Application.<br/><br/><b>Service Plan</b>&nbsp;means our service plan (whether for a Fixed Term or otherwise) chosen by you and set out in the Application or chosen by you through the now TV television portal.<br/><br/><b>Third Party Provider</b>&nbsp;means any third party provider which provides information or Content which is available for your access and use through the now TV services we provide.";
t_c_text[60]="<b>We or us </b>&nbsp;mean PCCW Media Limited.<br/><br/><b>You</b>&nbsp;means the customer who subscribes to the now TV services and as specified in the Application.";
		var page_num = 0;
	    
	iptvRegisterKeyHandler(keyEvent);

	function keyEvent(keyCode) {
		if (keyCode == KEY_BLUE || keyCode == KEY_UP) {
			if(page_num > 0){
				page_num--;
				if(page_num == 0){
					document.getElementById("footer_img").style.background="../../images/footer_next_e.jpg";
				}
				else{
					document.getElementById("footer_img").style.background="../../images/footer_pre_next_e.jpg";
				}
				document.getElementById("tc").innerHTML = t_c_text[page_num];
			}
		} else if (keyCode == KEY_YELLOW || keyCode == KEY_DOWN) {
			if(page_num < t_c_text.length-1){
				page_num++;
				if(page_num == t_c_text.length-1){
					document.getElementById("footer_img").style.background="../../images/footer_pre_e.jpg";
				}
				else{
					document.getElementById("footer_img").style.background="../../images/footer_pre_next_e.jpg";
				}
				document.getElementById("tc").innerHTML = t_c_text[page_num];
			}
		} else if(keyCode == KEY_BACK){
			if("select_plan"=="<%=status%>"){
				window.parent.location.href="<%=param%>&status=<%=status%>";
			}
			else if("top_up_and_deduction"=="<%=status%>"){
				window.parent.location.href="<%=param%>&status=<%=status%>&init_cur_option=<%=cur_option%>&init_option_offset=<%=option_offset%>";
			}
			else{
				iPanel.back();
			}
		}  
	}
	
	function load(){
		document.getElementById("tc").innerHTML = t_c_text[0];
		document.getElementById("footer_img").style.background="../../images/footer_next_e.jpg";
	}
    
    </script>
    
</head>

<body bgcolor="white" topmargin="0" leftmargin="0" class="bodyBg body_e" onLoad="load()">
	<table width="640" height="530" cellpadding="0" cellspacing="0" border="0">
		<!-- left table -->
		<tr>
        	<td width="165" height="495">
            	<table border="0" cellpadding="0" cellspacing="0">
                	<tr>
                    	<td width="165" height="70" class="logo"><img width="145" height="52" align="top" src="../../images/sd_video_express_e_ppv.png"></td>
                    </tr>
                    <tr>
                    	<td valign="top" width="165" height="330">
							<!-- left table text -->
                        	<table border="0" cellpadding="0" cellspacing="0">
                            	<tr>
                                	<td height="55"></td>
                                </tr>
                            	<tr>
                                	<td height="275" class="termConditionTxt paddingLeft13"><!--The now Select service Terms & Conditions (press MENU and select INFODESK to view) shall apply to your subscription of now Drama - Disney ABC (HD). Please press ENTER to confirm your acceptance of these Terms and Conditions and to subscribe to now Drama - Disney ABC.--></td>
                                </tr>
                            </table>
                        
                        </td>
                    </tr>
                    <tr>
                    	<td width="165" height="90" class="txtInfo01 paddingLeft10"><!--Press <img align="absmiddle" src="../../images/up_down_left_right_button.png"> and ENTER to select--></td>
                    </tr>
                    <tr>
                    	<td width="165" height="5"></td>
                    </tr>
                </table>
            </td>

		<!-- right table -->
            <td width="475" height="495">
                <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td height="36"><img width="475" height="36" border="0" src="../../images/back_exit_e.png"></td>                   
                    </tr>
                    <tr>
                      <td>
                            <table border="0" cellpadding="0" cellspacing="0" width="474" height="32" align="right">
                            <tr>
                                    <td height="4"></td>
                            </tr>
                            <tr>
                                    <td width="" height="32" class=" txt01 paddingLeft18">now Select Services Terms & Conditions</td>
                                </tr>
                                <tr>
                                    <td width="" height="17" ></td>
                                </tr>
                                <tr>
                                    <td id="tc" width="" height="406" class="paddingLeft18 paddingRight50 txtTC">
                                    	
                                    </td>
                                </tr>
                            </table>                        
                            <!--This library may provide content not suitable for viewers under 18 and that the subscriber is responsible for selling own parental lock preference.--></td>
                    </tr>
                    
                    <!--tr>
                    	<td height="5" colspan="3"></td>
                    </tr-->
                </table>
	        </td>
        </tr>
        
		<!-- footer -->
		<tr>
        	<td id="footer_img" colspan="2" width="640" height="35" background="../../images/footer_next_e.jpg">
			</td>
        </tr>
	</table>
</body>
</html>



